### ISSUE TITLE
Errors Out On NameCheap Shared Host

### ISSUE THREAD

**Issue by ghost** [imbrish/letsencrypt#1]
I am working with Namecheap's "Professional" hosting package,  connected to my host via SSH.
Running a "which php" gives me /usr/local/bin/php.
Running "/usr/local/bin/php -v" returns "PHP 5.3.29 (cli) (built: Jul 17 2017 19:21:27)"
Executed the following commands:
cd ~/;
git clone https://github.com/imbrish/letsencrypt;
cd letsencrypt;
composer install;
cp config.yml.example config.yml;
chmod 600 config.yml;
nano config.yml;
chmod 775 bin/letsencrypt;
bin/letsencrypt;

This generates the following error:
[10-Aug-2017 19:35:49 America/New_York] PHP Parse error:  syntax error, unexpected '[' in /home/(MyUsernameHere)/letsencrypt/bin/letsencrypt on line 37

**Comment by imbrish** [comment]
Looks like execution fails due to short array syntax which was introduced in [PHP 5.4.0](http://php.net/manual/en/migration54.new-features.php).

You could try to update your php, probably you can do it in cpanel. Alternatively you could backport the code by changing`[...]` to `array(...)`, this should probably suffice.

**Comment by ghost** [comment]
Many thanks for the response, that was the issue.  Changed my PHP version on my host to 7 and then re-tried my installation from scratch, worked perfectly!

Your installation guide is pretty much perfect except it doesn't specify the minimum PHP version. May be worth adding a couple lines about this particular thing to help out boneheads like myself who were running a super old version of PHP for no good reason. It is pretty straightforward to change the PHP version inside of cpanel in Software>Select PHP Version. I think I was on PHP 5.2 before, but honestly not sure what NameCheap's default is.

**Comment by imbrish** [comment]
Glad to help! Thanks for the feedback, just added "requirements" section to readme.
