### ISSUE TITLE
.well-known/acme-challenge is not created

### ISSUE THREAD

**Issue by vkyeswa** [imbrish/letsencrypt#3]
Providing payload at http://sub.example.com/.well-known/acme-challenge/jGl23eKOcXaChedNEqL4AWNSfMYtw-SrUutM-g4u4Ag

**Comment by imbrish** [comment]
What's the command output?

**Comment by vkyeswa** [comment]
i get that the domain is now authorized and Certificate issued but i don't get the ssl show up on the domain

**Comment by imbrish** [comment]
Check if certificate is displayed in the CPanel.

Else copy all the messages from `php bin/letsencrypt` and paste them here. There's not much I can do without seeing what exactly happens.
