### ISSUE TITLE
different config file from CLI

### ISSUE THREAD

**Issue by ghost** [imbrish/letsencrypt#5]
I know the script supports multiple domains inside the same config file. Does it support different config files from the cli, such as:

bin/letsencrypt domain1.config.yml
or 
bin/letsencrypt ./domain.config.yml

?

**Comment by imbrish** [comment]
Why would you need that? If you justify it good enough I may implement it, shouldn't take too much time :)

**Comment by ghost** [comment]
In my case, I have multiple wordpress installations under one account: 
/letsencrypt
/public_html/www.site1.com
/public_html/www.site2.com

Each site has its own SSL cert. 
I'd like to be able to configure letsencrypt to run with different jobs for different web sites. (better for debug, different check intervals under cron, etc.). I could accomplish the same think with multiple letsencrypt installations, but that seems awkward.

**Comment by Vincent-Noben** [comment]
I might add to that that in the case of multiple unrelated websites on the same server it is really confusing that the certificate also displays the names of the other unrelated websites. So an extra option to choose between "1 merged certificate for all websites" vs "a certificate per site & aliases" would be a very nice extra.

**Comment by imbrish** [comment]
@Vincent-Noben It was already possible to issue multiple certificates for different domains just by defining separate entries in the certificates section of the config. I updated the example.

**Comment by imbrish** [comment]
I added two ways to achieve issuing and installing certificates selectively:

1. As requested, define multiple configuration files and call `bin/letsencrypt --config=domain.config.yml`
2. Define all certificates together, but call them separately `bin/letsencrypt domain.com`.

More details in the readme.
